### ISSUE TITLE
sections requiring review

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/UserGuide#98]
##  ANALYSIS
- [x] aligning structures -- mention `match_atoms` etc: #73 
- [x] rms -- added `weights_groupselections`  #75 
- [x] contacts.Contacts -- added radius_cut_q #84
- [x] encore -- dres returns dimensionality reduction details instead of reference to self. hes does not accept details keyword anymore.
- [x] polymer.PersistenceLength #124
- [x] PCA (now correctly aligns; also some other fun new methods) #120
- [x] GNM -- removed `MassWeight` option #124

**Comment by lilyminium** [comment]
Closed in #73, #75, #84, #120, #124.
